#+TITLE:

最近在学校看到新生陆陆续续地来学校了，想起去年这个时候，也像他们一样怀着憧憬和好奇来到这里，短短一年的时间就这么过去了。回想这一年，虽然最错了很多的事情，但是还是明白了不少东西。如果不总结一下，总感觉这一年少了一些什么，正好之前说过要每周写一篇博客，正好就把这篇总结当成博客的文章吧。

* 学习
可以说大一在学习方面做得是非常糟糕的，从挂了四科这个结果就可以看出来（虽然有三门都补考了，另外一门大学语文因错过补考时间而直接重修），因为一开始就抱着错误的态度去看待这些，所以取得这样的后果也不感到太奇怪，虽然补考花去了一些时间和精力（总共复习了大概20小时左右），但是明白了一些事情也算没有白费。

除了专业课之外，其他的课程基本没有花时间，高数上册还是靠着高中的基础考过的（显然下册没那么容易了，所以就挂了-_-），如果再给我一年的时间，有些课程肯定要好好学了，当然没有如果，所以这些欠下来的债就需要以后花时间去还了。即使是一些不那么重要的课程，也不会抱着「只要过了」的心态去学习了，因为GPA总是越高越好的，把分刷高一点对以后申请也有帮助，要不然以后还要重新花时间重修刷分。

专业学习方面虽然比其他科目认真了一点，但是实际上也没有花太多的时间在上面。大一上的C语言课基本没去，大一下的C++直接免修了（C++根本就不会，C语言也学得像Shit）。唯一好好上的一门课是一门专业选修课，名字叫「研究性学习A」，实际上也是讲的C语言，只不过比专业内开的必修课难度大了点。上完这门课的收获还是挺大的，至少学会怎么写程序了，下学期又继续参加了「研究性学习B」，学习的是Java。不过相比较研A，研B的收获就没有那么大了，除了会了Java的语法之外，并没有学习到太多的知识，所以今年就没有继续参加研C了。

通过这些专业课的学习，发现自己大部分的专业知识都是通过自己看书获得的，从课堂上获得的知识很少。如果抛去科学部分，CS这个专业很显然是一门需要动手的课程，只是看书的话，可能一上手写代码就蒙了。

上学期的时候还看了《SICP》，可惜在第一章就被习题卡住了，就没有继续看下去。现在想想，应该先把那些习题跳过的，所以这本书就好用大二的时间来看完了。

英语水平比高中的时候稍微高了一点，虽然学校的英语课基本没去过，但是每天依然坚持阅读英文的文章，所以不至于对英文过于陌生。裸考过了四级，分数不高，也没有什么值得说的。


* 感情
大一下学期谈了一次恋爱，不过最后以 =bad ending= 结束了。
